Missing dependency:
  File "/opt/src/buildout.coredev/src/Products.CMFEditions/Products/CMFEditions/StandardModifiers.py", line 33, in <module>
    from zope.copy import copy
ImportError: No module named copy